services:
  app:
      build: .
      container_name: api-checklist
      ports:
        - "8080:8080"
      volumes:
        - ./src:/app/src
        - ./uploads:/app/uploads
      env_file:
        - .env
      environment:
        SPRING_DATASOURCE_URL: ${DB_URL}
        SPRING_DATASOURCE_USERNAME: ${DB_USER}
        SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
        SPRING_JPA_HIBERNATE_DDL_AUTO: none
        SPRING_DEVTOOLS_RESTART_ENABLED: "true"
        SPRING_DEVTOOLS_RESTART_ADDITIONAL_PATHS: "src/main/java"
        SPRING_DEVTOOLS_RESTART_POLL_INTERVAL: "1000ms"

  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: